image: Visual Studio 2019
init:
  - git config --global core.autocrlf false
install:
  - dotnet --version
  - dotnet restore
build_script:
  - dotnet build
after_build:
  #Generates the publish folder for deployment
  - dotnet publish -c Release -r linux-arm
artifacts:
  - path: Navigator\bin\Release\netcoreapp2.2\linux-arm\publish
test_script:
  - dotnet test --logger:Appveyor