image: Visual Studio 2019
init:
  - git config --global core.autocrlf true
install:
  - dotnet --version
  - dotnet restore
build_script:
- dotnet build
before_build:
- appveyor-retry dotnet restore -v Minimal
test:
  - Navigator.Tests.dll