// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Navigator.DAL;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Navigator.Migrations.Migrations
{
    [DbContext(typeof(NavigatorContext))]
    partial class NavigatorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Navigator.DAL.Navigator.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("From");

                    b.Property<string>("NavigatedSystems");

                    b.Property<int>("To");

                    b.HasKey("RouteId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Navigator.DAL.Navigator.ScoutData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CachedTime");

                    b.Property<DateTime>("EarliestExpiryTime");

                    b.Property<string>("EveScoutData");

                    b.Property<string>("SolarSystemName");

                    b.HasKey("Id");

                    b.ToTable("EveScoutData");
                });
#pragma warning restore 612, 618
        }
    }
}
